# Form implementation generated from reading ui file '/home/develpment/AIV/Projects/Pokayoke/GUI/Qt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(345, 305)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("background:#232423")
        MainWindow.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tipMsg = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tipMsg.setGeometry(QtCore.QRect(10, 10, 324, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tipMsg.setFont(font)
        self.tipMsg.setStyleSheet("background:#84bcf0;color:darkblack;text-align: center;")
        self.tipMsg.setPlaceholderText("")
        self.tipMsg.setObjectName("tipMsg")
        self.lable_tl = QtWidgets.QLabel(parent=self.centralwidget)
        self.lable_tl.setGeometry(QtCore.QRect(10, 88, 160, 90))
        self.lable_tl.setStyleSheet("background:gray;color:black;border-color:black")
        self.lable_tl.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lable_tl.setText("")
        self.lable_tl.setObjectName("lable_tl")
        self.label_tr = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_tr.setGeometry(QtCore.QRect(175, 88, 160, 90))
        self.label_tr.setStyleSheet("background:gray;color:black")
        self.label_tr.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_tr.setText("")
        self.label_tr.setObjectName("label_tr")
        self.label_bl = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_bl.setGeometry(QtCore.QRect(10, 183, 160, 90))
        self.label_bl.setStyleSheet("background:gray;color:black")
        self.label_bl.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_bl.setText("")
        self.label_bl.setObjectName("label_bl")
        self.label_br = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_br.setGeometry(QtCore.QRect(175, 183, 160, 90))
        self.label_br.setStyleSheet("background:gray;color:black")
        self.label_br.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_br.setText("")
        self.label_br.setObjectName("label_br")
        self.mistakeMsg = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.mistakeMsg.setGeometry(QtCore.QRect(13, 125, 319, 110))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mistakeMsg.setFont(font)
        self.mistakeMsg.setStyleSheet("background:gray;color:black")
        self.mistakeMsg.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.mistakeMsg.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.mistakeMsg.setLineWidth(1)
        self.mistakeMsg.setObjectName("mistakeMsg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZKW Validator"))
