# Form implementation generated from reading ui file 'C:\Main\Repositories\Validator\GUI\Qt.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1010, 650)
        font = QtGui.QFont()
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Main\\Repositories\\Validator\\GUI\\icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background:#232423")
        MainWindow.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_positions = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_positions.setGeometry(QtCore.QRect(515, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title_positions.setFont(font)
        self.title_positions.setAutoFillBackground(False)
        self.title_positions.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.title_positions.setObjectName("title_positions")
        self.label_LH1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_LH1.setGeometry(QtCore.QRect(590, 50, 400, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_LH1.setFont(font)
        self.label_LH1.setStyleSheet("background:gray;color:black;border-color:black;border-radius: 10px;")
        self.label_LH1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_LH1.setText("")
        self.label_LH1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_LH1.setObjectName("label_LH1")
        self.lable_RH1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lable_RH1.setGeometry(QtCore.QRect(185, 50, 400, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lable_RH1.setFont(font)
        self.lable_RH1.setStyleSheet("background:gray;color:black;border-color:black;border-radius: 10px;")
        self.lable_RH1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lable_RH1.setText("")
        self.lable_RH1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.lable_RH1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lable_RH1.setObjectName("lable_RH1")
        self.label_LH2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_LH2.setGeometry(QtCore.QRect(590, 155, 400, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_LH2.setFont(font)
        self.label_LH2.setStyleSheet("background:gray;color:black;border-color:black;border-radius: 10px;")
        self.label_LH2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_LH2.setText("")
        self.label_LH2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_LH2.setObjectName("label_LH2")
        self.label_RH2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_RH2.setGeometry(QtCore.QRect(185, 155, 400, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_RH2.setFont(font)
        self.label_RH2.setStyleSheet("background:gray;color:black;border-color:black;border-radius: 10px;")
        self.label_RH2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_RH2.setText("")
        self.label_RH2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_RH2.setObjectName("label_RH2")
        self.tip_msg = QtWidgets.QLabel(parent=self.centralwidget)
        self.tip_msg.setGeometry(QtCore.QRect(185, 280, 805, 210))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tip_msg.setFont(font)
        self.tip_msg.setStyleSheet("background:#84bcf0;color:darkblack;text-align: center;border-radius: 10px;")
        self.tip_msg.setText("")
        self.tip_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tip_msg.setWordWrap(True)
        self.tip_msg.setObjectName("tip_msg")
        self.mistake_msg = QtWidgets.QLabel(parent=self.centralwidget)
        self.mistake_msg.setGeometry(QtCore.QRect(185, 280, 805, 210))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mistake_msg.setFont(font)
        self.mistake_msg.setStyleSheet("background-color: rgb(31, 31, 31);")
        self.mistake_msg.setText("")
        self.mistake_msg.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mistake_msg.setWordWrap(True)
        self.mistake_msg.setObjectName("mistake_msg")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(185, 520, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(185, 560, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(185, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_PCB1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_PCB1.setGeometry(QtCore.QRect(310, 522, 680, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_PCB1.setFont(font)
        self.label_PCB1.setStyleSheet("background:gray;color:black;border-color:black;border-radius: 10px;")
        self.label_PCB1.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_PCB1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCB1.setObjectName("label_PCB1")
        self.label_PCB2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_PCB2.setGeometry(QtCore.QRect(310, 562, 680, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_PCB2.setFont(font)
        self.label_PCB2.setStyleSheet("background:gray;color:black;border-color:black;border-radius: 10px;")
        self.label_PCB2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_PCB2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_PCB2.setObjectName("label_PCB2")
        self.label_heat = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_heat.setGeometry(QtCore.QRect(310, 602, 680, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_heat.setFont(font)
        self.label_heat.setStyleSheet("background:gray;color:black;border-color:black;border-radius: 10px;")
        self.label_heat.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_heat.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_heat.setObjectName("label_heat")
        self.btn_fill = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_fill.setGeometry(QtCore.QRect(0, 0, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_fill.setFont(font)
        self.btn_fill.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_fill.setCheckable(True)
        self.btn_fill.setObjectName("btn_fill")
        self.btn_pick = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_pick.setGeometry(QtCore.QRect(0, 80, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_pick.setFont(font)
        self.btn_pick.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_pick.setCheckable(True)
        self.btn_pick.setObjectName("btn_pick")
        self.btn_scan_1 = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_scan_1.setGeometry(QtCore.QRect(0, 160, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_scan_1.setFont(font)
        self.btn_scan_1.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_scan_1.setCheckable(True)
        self.btn_scan_1.setObjectName("btn_scan_1")
        self.btn_scan_2 = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_scan_2.setGeometry(QtCore.QRect(0, 240, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_scan_2.setFont(font)
        self.btn_scan_2.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_scan_2.setCheckable(True)
        self.btn_scan_2.setObjectName("btn_scan_2")
        self.btn_print = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_print.setGeometry(QtCore.QRect(0, 320, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_print.setFont(font)
        self.btn_print.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_print.setCheckable(True)
        self.btn_print.setObjectName("btn_print")
        self.btn_scan_3 = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_scan_3.setGeometry(QtCore.QRect(0, 400, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_scan_3.setFont(font)
        self.btn_scan_3.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_scan_3.setCheckable(True)
        self.btn_scan_3.setObjectName("btn_scan_3")
        self.btn_valid = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_valid.setGeometry(QtCore.QRect(0, 480, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_valid.setFont(font)
        self.btn_valid.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_valid.setCheckable(True)
        self.btn_valid.setObjectName("btn_valid")
        self.btn_reserve = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btn_reserve.setGeometry(QtCore.QRect(0, 560, 170, 90))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btn_reserve.setFont(font)
        self.btn_reserve.setStyleSheet("/* Default (Unchecked) State */\n"
"QToolButton {\n"
"\n"
"}\n"
"\n"
"/* Checked State */\n"
"QToolButton:checked {\n"
"    background-color: green;\n"
"}")
        self.btn_reserve.setText("")
        self.btn_reserve.setObjectName("btn_reserve")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Validacion ZKW"))
        self.title_positions.setText(_translate("MainWindow", "Posiciones"))
        self.label.setText(_translate("MainWindow", "PCB1"))
        self.label_2.setText(_translate("MainWindow", "PCB2"))
        self.label_3.setText(_translate("MainWindow", "Heatsink"))
        self.label_PCB1.setText(_translate("MainWindow", "114400505908QEBUF0601400061"))
        self.label_PCB2.setText(_translate("MainWindow", "114400505908QEBUF0601400062"))
        self.label_heat.setText(_translate("MainWindow", "1144.006.06300000000000058Q"))
        self.btn_fill.setText(_translate("MainWindow", "PUT ALL"))
        self.btn_pick.setText(_translate("MainWindow", "PICK ONE"))
        self.btn_scan_1.setText(_translate("MainWindow", "SCAN PCB 1"))
        self.btn_scan_2.setText(_translate("MainWindow", "SCAN PCB 2"))
        self.btn_print.setText(_translate("MainWindow", "PRINTING"))
        self.btn_scan_3.setText(_translate("MainWindow", "SCAN\n"
"HEATSINK"))
        self.btn_valid.setText(_translate("MainWindow", "VALIDATION"))
